name: CI/CD with Terraform

on:
  push:
    branches:
      - main

jobs:
  start-runner:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: Start self-hosted EC2 runner
    permissions:
      actions: write

    env:
      GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
      EC2_INSTANCE_TYPE: "c5.4xlarge"
      EC2_AMI_ID: "ami-04fb1f1655deb8bb8"
      EC2_SUBNET_ID: "subnet-015014d9e9bfd7242"
      EC2_SECURITY_GROUP_ID: "sg-04137bc46731e526b"
      EC2_INSTANCE_TTL: 40                # Optional (default is 60 minutes)
      EC2_SPOT_INSTANCE_STRATEGY: "SpotOnly"

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Start EC2 Runner
        id: start-ec2-runner
        uses: NextChapterSoftware/ec2-action-builder@v1.5
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          aws_access_key_id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ env.AWS_REGION }}
          ec2_instance_type: ${{ env.EC2_INSTANCE_TYPE }}
          ec2_ami_id: ${{ env.EC2_AMI_ID }}
          ec2_subnet_id: ${{ env.EC2_SUBNET_ID }}
          ec2_security_group_id: ${{ env.EC2_SECURITY_GROUP_ID }}
          ec2_instance_ttl: ${{ env.EC2_INSTANCE_TTL }}
          ec2_spot_instance_strategy: ${{ env.EC2_SPOT_INSTANCE_STRATEGY }}
          ec2_instance_tags: null

  run-build:
    runs-on: self-hosted

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    needs: start-runner

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install Terraform
        run: |
          sudo yum install -y yum-utils
          sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
          sudo yum -y install terraform
          terraform --version

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ env.AWS_S3_BUCKET }}" -backend-config="key=terraform.tfstate" -backend-config="region=${{ env.AWS_DEFAULT_REGION }}"

      - name: Terraform Apply
        run: terraform destroy -auto-approve
